// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZooCode.Models
{    
    public class Zoo
    {                        
        public int ZooID { get; set; }        
        [StringLength(30)]
        [Display(Name = "Zoo Name")]
        [Required(ErrorMessage = "Please enter the name of the zoo")]
        public string Zoo_name { get; set; }        
        [StringLength(50)]
        [Display(Name = "Zoo Address")]
        [Required(ErrorMessage = "Please enter the address of the zoo")]
        public string Zoo_address { get; set; }

        
        public virtual ICollection<ZooAnimal> ZooAnimalCollection { get; set; }
    }
}