// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZooCode.Models
{
    public class ZooAnimal
    {
        public int ZooAnimalID { get; set; }
        public int ZooID { get; set; }
        public Zoo Zoo { get; set; }                       
        public int AnimalID { get; set; }
        public Animal Animal { get; set; }

        //[ForeignKey(nameof(Animal_id))]
        //[InverseProperty("ZooAnimals")]
       
        //[ForeignKey(nameof(ZooAnimal_id))]
        //[InverseProperty("ZooAnimals")]        
    }
}